### ISSUE TITLE
Small Caps idea

### ISSUE THREAD

**Issue by luxuryluke** [scottboms/kirby-markup#1]
Is it part of the scope of this collection of buttons to have something that makes small caps or is small caps just a styling of these sorts of elements, would you say?

**Comment by scottboms** [comment]
I guess it depends on what you were thinking in terms of implementation. If it's a case where there's a localized need within a paragraph that can't be easily handled by CSS alone and it would help to wrap some text in an element, then yes. The question then becomes is there a best practice element (`span` I would guess) and also presumably a class to hook onto.

**Comment by scottboms** [comment]
And just like that... it's in version 1.0.1 :)

**Comment by luxuryluke** [comment]
oh, thank you very much!
